### ISSUE TITLE
Getting started weird issue

### ISSUE THREAD

**Issue by codams** [scottashipp/noted#5]
Hi, I had to `git -C $HOME/Documents clone git@github.com:scottashipp/noted.git` instead of `git clone git@github.com:scottashipp/noted.git -C $HOME/Documents`.

I'm on mac w/ iterm2 but I don't have another env to test.

Have a good dayyy

**Comment by codams** [comment]
Done 😀

**Comment by shrihanDev** [comment]
Just a tidbit: The `-C` option and the regular `git <repo_path> <clone_output_dir>`, while seem to do the same thing, they actually aren't:

> -C <path>
> Run as if git was started in <path> instead of the current working directory. When multiple -C options are given, each subsequent non-absolute -C <path> is interpreted relative to the preceding -C <path>. If <path> is present but empty, e.g. -C "", then the current working directory is left unchanged.

> This option affects options that expect path name like --git-dir and --work-tree in that their interpretations of the path names would be made relative to the working directory caused by the -C option. For example the following invocations are equivalent:

> ```bash
> git --git-dir=a.git --work-tree=b -C c status
> git --git-dir=c/a.git --work-tree=c/b status
> ```

Good day1
