### ISSUE TITLE
Plz remove the leading newline when creating new note

### ISSUE THREAD

**Issue by Xiangze-Li** [scottashipp/noted#8]
I noticed every time new notes are created, a leading and a tailing newline will be added to the template. If the template has YAML front matter, the leading newline may cause error parsing the YAML. Please consider remove the leading newline

**Comment by scottashipp** [comment]
Hi @Xiangze-Li ! I'm not too familiar with this use case. Can you explain further? Why would markdown files have YAML front matter? _noted_ explicitly supports Markdown only right now, like the About mentions:

> Lightweight CLI for taking _markdown_ notes . . .

But if there is a use case where not having the new lines added in is better for some users, we can probably incorporate this in the next release into a config option?

**Comment by Xiangze-Li** [comment]
Thanks for replying! I read a blog about use *noted* to take notes then use *hugo* or other tools to generate a website from all the md files. With YAML front matter, I can add some metadata to the pages, like:

```markdown
---
author: XXX
date: TIMESTAMP
---

# HEADERTEXT
```

If there's no leading newline, everything will work just fine. 

Thanks again!

**Comment by scottashipp** [comment]
@Xiangze-Li Hi! Sorry for the delay here. We had a holiday on Monday in the US so I was gone over the weekend.

OK so it sounds like you just need to configure a custom template file for your use case. This is already supported by _noted_! :tada: 

Please refer to the [section on custom configuration](https://github.com/scottashipp/noted#configuring-custom-values) where you will set up a `.notedconfig` file with a `NOTED_TEMPLATE_FILE` property. The value of this property should be the path to your own template file. It explains it all in the link. 

Let me know if you have any questions or any issues with it.

**Comment by Xiangze-Li** [comment]
Hi! I tried the custom template config again, it worked this time. I must have made some mistakes last time I edit the template. 

Sorry for these trouble. Many thanks for your assistance! And wish you a happy holiday!
